# Every number in the README is regenerated by a target in this file.
# If a figure cannot be produced by one of these, it does not belong in the
# README.

COMPOSE := docker compose
RUN     := $(COMPOSE) run --rm app python -m

.DEFAULT_GOAL := help

.PHONY: help
help:  ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

# --- infrastructure -------------------------------------------------------

.PHONY: up
up:  ## Start Postgres + app, wait until the database is healthy
	$(COMPOSE) up -d --build
	@echo "waiting for postgres..."
	@$(COMPOSE) exec -T db sh -c 'until pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} >/dev/null 2>&1; do sleep 1; done'
	@echo "up. postgres on localhost:5434, api on localhost:8000"

.PHONY: down
down:  ## Stop containers, keep the data volume
	$(COMPOSE) down

.PHONY: nuke
nuke:  ## Stop containers AND destroy the data volume (loses the corpus)
	$(COMPOSE) down -v

.PHONY: migrate
migrate:  ## Reapply migrations against a running database
	@for f in migrations/*.sql; do \
		echo "applying $$f"; \
		$(COMPOSE) exec -T db psql -v ON_ERROR_STOP=1 -U $${POSTGRES_USER:-aml} -d $${POSTGRES_DB:-aml} < $$f; \
	done

.PHONY: psql
psql:  ## Open a psql shell against the running database
	$(COMPOSE) exec db psql -U $${POSTGRES_USER:-aml} -d $${POSTGRES_DB:-aml}

.PHONY: logs
logs:  ## Tail application logs
	$(COMPOSE) logs -f app

# --- corpus ---------------------------------------------------------------

.PHONY: fetch
fetch:  ## Download every document in corpus/manifest.yaml
	$(RUN) aml_agent.ingest.download

.PHONY: ingest
ingest:  ## Download, extract, chunk, embed and load the whole corpus
	$(RUN) aml_agent.ingest.pipeline

.PHONY: corpus-stats
corpus-stats:  ## Print document and chunk counts per chunk profile
	$(RUN) aml_agent.ingest.stats

# --- evaluation -----------------------------------------------------------

.PHONY: eval
eval: eval-retrieval eval-answers  ## Regenerate every number in the README

.PHONY: eval-retrieval
eval-retrieval:  ## M1: recall@5, recall@10, MRR for BM25 / dense / hybrid
	$(RUN) aml_agent.evaluation.retrieval

.PHONY: eval-answers
eval-answers:  ## M4: groundedness, citation validity, refusal accuracy
	$(RUN) aml_agent.evaluation.answers

.PHONY: judge-audit
judge-audit:  ## Sample 20 judge decisions into results/judge_agreement.md for grading
	$(RUN) aml_agent.evaluation.judge_audit

.PHONY: judge-audit-score
judge-audit-score:  ## After grading, compute the judge-human disagreement rate
	$(RUN) aml_agent.evaluation.judge_audit --score

.PHONY: report
report:  ## Rewrite the README results tables from results/*.json
	$(RUN) aml_agent.evaluation.report

# --- service --------------------------------------------------------------

.PHONY: serve
serve:  ## Run the API in the foreground
	$(COMPOSE) up app

.PHONY: ask
ask:  ## Ask one question end to end. Usage: make ask Q="your question"
	$(RUN) aml_agent.agent.cli "$(Q)"

# --- development ----------------------------------------------------------

.PHONY: test
test:  ## Run the test suite
	$(COMPOSE) run --rm app python -m pytest -q

.PHONY: shell
shell:  ## Shell inside the app container
	$(COMPOSE) run --rm app bash
